# FlexCore Linting Configuration
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 10

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  goimports:
    local-prefixes: github.com/flext/flexcore

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 15

  nestif:
    min-complexity: 5

  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - structcheck
    - deadcode
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - lll
    - goconst
    - gocritic
    - gocognit
    - funlen
    - nestif
    - gomnd
    - exportloopref
    - depguard
    - dogsled
    - dupl
    - forbidigo
    - nakedret
    - prealloc
    - scopelint
    - unconvert
    - unparam
    - whitespace

  disable:
    - maligned  # deprecated
    - interfacer  # deprecated

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - dupl
        
    - path: cmd/
      linters:
        - gocyclo
        - funlen

    - path: internal/infrastructure/
      linters:
        - nestif
        
  max-issues-per-linter: 0
  max-same-issues: 0