# FlexCore Linting Configuration
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    shadow: true
    enable-all: true

  gocyclo:
    min-complexity: 10

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  goimports:
    local-prefixes: github.com/flext-sh/flexcore

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 15

  nestif:
    min-complexity: 5

  mnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign

  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/flext-sh/flexcore
          - github.com/flext-sh/flext
          - github.com/gin-gonic/gin
          - github.com/hashicorp/go-plugin
          - github.com/lib/pq
          - github.com/mattn/go-sqlite3
          - github.com/google/uuid
          - github.com/stretchr/testify
          - go.uber.org/zap
          - github.com/redis/go-redis/v9
          - google.golang.org/grpc

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - lll
    - goconst
    - gocritic
    - gocognit
    - funlen
    - nestif
    - mnd
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - forbidigo
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - whitespace

  disable: []

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - dupl

    - path: cmd/
      linters:
        - gocyclo
        - funlen

    - path: internal/infrastructure/
      linters:
        - nestif

  max-issues-per-linter: 0
  max-same-issues: 0
