from _typeshed import Incomplete

class FlexCore:
    config: Incomplete
    def __init__(self, config: dict[str, object] | None = None) -> None: ...
    def initialize(self) -> None: ...
    def is_initialized(self) -> bool: ...
    def shutdown(self) -> None: ...
