// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: data_processor_interface.proto

package plugins

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Process request message
type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InputFormat   string                 `protobuf:"bytes,3,opt,name=input_format,json=inputFormat,proto3" json:"input_format,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_data_processor_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_processor_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_data_processor_interface_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProcessRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProcessRequest) GetInputFormat() string {
	if x != nil {
		return x.InputFormat
	}
	return ""
}

func (x *ProcessRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

// Process response message
type ProcessResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Data             []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Success          bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_data_processor_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_processor_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_data_processor_interface_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProcessResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProcessResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Info request message
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_data_processor_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_processor_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_data_processor_interface_proto_rawDescGZIP(), []int{2}
}

// Info response message
type InfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SupportedFormats []string               `protobuf:"bytes,4,rep,name=supported_formats,json=supportedFormats,proto3" json:"supported_formats,omitempty"`
	Capabilities     map[string]string      `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_data_processor_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_processor_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_data_processor_interface_proto_rawDescGZIP(), []int{3}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfoResponse) GetSupportedFormats() []string {
	if x != nil {
		return x.SupportedFormats
	}
	return nil
}

func (x *InfoResponse) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Health request message
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_data_processor_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_processor_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_data_processor_interface_proto_rawDescGZIP(), []int{4}
}

// Health response message
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_data_processor_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_processor_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_data_processor_interface_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_data_processor_interface_proto protoreflect.FileDescriptor

const file_data_processor_interface_proto_rawDesc = "" +
	"\n" +
	"\x1edata_processor_interface.proto\x12\x10flexcore.plugins\"\xf5\x01\n" +
	"\x0eProcessRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12J\n" +
	"\bmetadata\x18\x02 \x03(\v2..flexcore.plugins.ProcessRequest.MetadataEntryR\bmetadata\x12!\n" +
	"\finput_format\x18\x03 \x01(\tR\vinputFormat\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\x0fProcessResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12K\n" +
	"\bmetadata\x18\x02 \x03(\v2/.flexcore.plugins.ProcessResponse.MetadataEntryR\bmetadata\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x03R\x10processingTimeMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\r\n" +
	"\vInfoRequest\"\xa2\x02\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x11supported_formats\x18\x04 \x03(\tR\x10supportedFormats\x12T\n" +
	"\fcapabilities\x18\x05 \x03(\v20.flexcore.plugins.InfoResponse.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\\\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xf6\x01\n" +
	"\rDataProcessor\x12N\n" +
	"\aProcess\x12 .flexcore.plugins.ProcessRequest\x1a!.flexcore.plugins.ProcessResponse\x12H\n" +
	"\aGetInfo\x12\x1d.flexcore.plugins.InfoRequest\x1a\x1e.flexcore.plugins.InfoResponse\x12K\n" +
	"\x06Health\x12\x1f.flexcore.plugins.HealthRequest\x1a .flexcore.plugins.HealthResponseB#Z!github.com/flext/flexcore/pluginsb\x06proto3"

var (
	file_data_processor_interface_proto_rawDescOnce sync.Once
	file_data_processor_interface_proto_rawDescData []byte
)

func file_data_processor_interface_proto_rawDescGZIP() []byte {
	file_data_processor_interface_proto_rawDescOnce.Do(func() {
		file_data_processor_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_processor_interface_proto_rawDesc), len(file_data_processor_interface_proto_rawDesc)))
	})
	return file_data_processor_interface_proto_rawDescData
}

var file_data_processor_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_data_processor_interface_proto_goTypes = []any{
	(*ProcessRequest)(nil),  // 0: flexcore.plugins.ProcessRequest
	(*ProcessResponse)(nil), // 1: flexcore.plugins.ProcessResponse
	(*InfoRequest)(nil),     // 2: flexcore.plugins.InfoRequest
	(*InfoResponse)(nil),    // 3: flexcore.plugins.InfoResponse
	(*HealthRequest)(nil),   // 4: flexcore.plugins.HealthRequest
	(*HealthResponse)(nil),  // 5: flexcore.plugins.HealthResponse
	nil,                     // 6: flexcore.plugins.ProcessRequest.MetadataEntry
	nil,                     // 7: flexcore.plugins.ProcessResponse.MetadataEntry
	nil,                     // 8: flexcore.plugins.InfoResponse.CapabilitiesEntry
}
var file_data_processor_interface_proto_depIdxs = []int32{
	6, // 0: flexcore.plugins.ProcessRequest.metadata:type_name -> flexcore.plugins.ProcessRequest.MetadataEntry
	7, // 1: flexcore.plugins.ProcessResponse.metadata:type_name -> flexcore.plugins.ProcessResponse.MetadataEntry
	8, // 2: flexcore.plugins.InfoResponse.capabilities:type_name -> flexcore.plugins.InfoResponse.CapabilitiesEntry
	0, // 3: flexcore.plugins.DataProcessor.Process:input_type -> flexcore.plugins.ProcessRequest
	2, // 4: flexcore.plugins.DataProcessor.GetInfo:input_type -> flexcore.plugins.InfoRequest
	4, // 5: flexcore.plugins.DataProcessor.Health:input_type -> flexcore.plugins.HealthRequest
	1, // 6: flexcore.plugins.DataProcessor.Process:output_type -> flexcore.plugins.ProcessResponse
	3, // 7: flexcore.plugins.DataProcessor.GetInfo:output_type -> flexcore.plugins.InfoResponse
	5, // 8: flexcore.plugins.DataProcessor.Health:output_type -> flexcore.plugins.HealthResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_data_processor_interface_proto_init() }
func file_data_processor_interface_proto_init() {
	if File_data_processor_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_processor_interface_proto_rawDesc), len(file_data_processor_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_processor_interface_proto_goTypes,
		DependencyIndexes: file_data_processor_interface_proto_depIdxs,
		MessageInfos:      file_data_processor_interface_proto_msgTypes,
	}.Build()
	File_data_processor_interface_proto = out.File
	file_data_processor_interface_proto_goTypes = nil
	file_data_processor_interface_proto_depIdxs = nil
}
